-- Generated from fle/commons/observation/buildability_channels.json.
return { id = "83db48f2c5fa", channels = {
  {name = "accumulator", direction = 0, members = {"accumulator"}},
  {name = "active-provider-chest", direction = 0, members = {"active-provider-chest", "buffer-chest", "constant-combinator", "iron-chest", "passive-provider-chest", "requester-chest", "steel-chest", "storage-chest", "wooden-chest"}},
  {name = "arithmetic-combinator", direction = 0, members = {"arithmetic-combinator", "decider-combinator"}},
  {name = "arithmetic-combinator", direction = 4, members = {"arithmetic-combinator", "decider-combinator"}},
  {name = "artillery-turret", direction = 0, members = {"artillery-turret", "assembling-machine-1", "assembling-machine-2", "assembling-machine-3", "beacon", "centrifuge", "chemical-plant", "electric-furnace", "lab", "radar"}},
  {name = "big-electric-pole", direction = 0, members = {"big-electric-pole"}},
  {name = "boiler", direction = 0, members = {"boiler", "heat-exchanger"}},
  {name = "boiler", direction = 4, members = {"boiler", "heat-exchanger"}},
  {name = "boiler", direction = 8, members = {"boiler", "heat-exchanger"}},
  {name = "boiler", direction = 12, members = {"boiler", "heat-exchanger"}},
  {name = "bulk-inserter", direction = 0, members = {"bulk-inserter", "burner-inserter", "fast-inserter", "inserter", "long-handed-inserter", "medium-electric-pole", "small-electric-pole", "small-lamp"}},
  {name = "burner-mining-drill", direction = 0, members = {"burner-mining-drill"}},
  {name = "car", direction = 0, members = {"car"}},
  {name = "car", direction = 4, members = {"car"}},
  {name = "cargo-wagon", direction = 0, members = {"cargo-wagon", "fluid-wagon"}},
  {name = "cargo-wagon", direction = 4, members = {"cargo-wagon", "fluid-wagon"}},
  {name = "electric-mining-drill", direction = 0, members = {"electric-mining-drill"}},
  {name = "express-splitter", direction = 0, members = {"express-splitter", "fast-splitter", "splitter"}},
  {name = "express-splitter", direction = 4, members = {"express-splitter", "fast-splitter", "splitter"}},
  {name = "express-transport-belt", direction = 0, members = {"express-transport-belt", "express-underground-belt", "fast-transport-belt", "fast-underground-belt", "transport-belt", "underground-belt"}},
  {name = "flamethrower-turret", direction = 0, members = {"flamethrower-turret"}},
  {name = "flamethrower-turret", direction = 4, members = {"flamethrower-turret"}},
  {name = "gate", direction = 0, members = {"gate"}},
  {name = "gate", direction = 4, members = {"gate"}},
  {name = "gun-turret", direction = 0, members = {"gun-turret", "laser-turret", "power-switch", "steel-furnace", "stone-furnace", "substation"}},
  {name = "heat-pipe", direction = 0, members = {"heat-pipe"}},
  {name = "land-mine", direction = 0, members = {"land-mine"}},
  {name = "locomotive", direction = 0, members = {"locomotive"}},
  {name = "locomotive", direction = 4, members = {"locomotive"}},
  {name = "nuclear-reactor", direction = 0, members = {"nuclear-reactor"}},
  {name = "offshore-pump", direction = 0, members = {"offshore-pump"}},
  {name = "offshore-pump", direction = 4, members = {"offshore-pump"}},
  {name = "offshore-pump", direction = 8, members = {"offshore-pump"}},
  {name = "offshore-pump", direction = 12, members = {"offshore-pump"}},
  {name = "oil-refinery", direction = 0, members = {"oil-refinery"}},
  {name = "pipe", direction = 0, members = {"pipe", "stone-wall"}},
  {name = "pipe-to-ground", direction = 0, members = {"pipe-to-ground"}},
  {name = "pipe-to-ground", direction = 4, members = {"pipe-to-ground"}},
  {name = "pipe-to-ground", direction = 8, members = {"pipe-to-ground"}},
  {name = "pipe-to-ground", direction = 12, members = {"pipe-to-ground"}},
  {name = "programmable-speaker", direction = 0, members = {"programmable-speaker"}},
  {name = "pump", direction = 0, members = {"pump"}},
  {name = "pump", direction = 4, members = {"pump"}},
  {name = "pumpjack", direction = 0, members = {"pumpjack"}},
  {name = "straight-rail", direction = 0, members = {"straight-rail"}},
  {name = "straight-rail", direction = 4, members = {"straight-rail"}},
  {name = "rail-chain-signal", direction = 0, members = {"rail-chain-signal", "rail-signal"}},
  {name = "rail-chain-signal", direction = 4, members = {"rail-chain-signal", "rail-signal"}},
  {name = "rail-chain-signal", direction = 8, members = {"rail-chain-signal", "rail-signal"}},
  {name = "rail-chain-signal", direction = 12, members = {"rail-chain-signal", "rail-signal"}},
  {name = "roboport", direction = 0, members = {"roboport"}},
  {name = "rocket-silo", direction = 0, members = {"rocket-silo"}},
  {name = "solar-panel", direction = 0, members = {"solar-panel"}},
  {name = "spidertron", direction = 0, members = {"spidertron"}},
  {name = "steam-engine", direction = 0, members = {"steam-engine", "steam-turbine"}},
  {name = "steam-engine", direction = 4, members = {"steam-engine", "steam-turbine"}},
  {name = "storage-tank", direction = 0, members = {"storage-tank"}},
  {name = "tank", direction = 0, members = {"tank"}},
  {name = "tank", direction = 4, members = {"tank"}},
  {name = "train-stop", direction = 0, members = {"train-stop"}},
  {name = "train-stop", direction = 4, members = {"train-stop"}},
  {name = "train-stop", direction = 8, members = {"train-stop"}},
  {name = "train-stop", direction = 12, members = {"train-stop"}},
}}
